from __future__ import annotations

from typing import Iterable


def _pdf_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _ascii(value: object) -> str:
    text = str(value if value is not None else "-")
    return text.encode("latin-1", "replace").decode("latin-1")


def _wrap(text: str, width: int = 92) -> list[str]:
    words = _ascii(text).split()
    if not words:
        return [""]
    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if len(candidate) <= width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def render_report_pdf(snapshot: dict) -> bytes:
    """Render a small deterministic PDF using built-in Helvetica only.

    The PDF is intentionally text-first so it can be generated on Vercel without
    native PDF dependencies. The complete immutable report snapshot remains in
    PostgreSQL JSONB; this binary is the portable signed-off presentation copy.
    """
    project = snapshot.get("project", {})
    run = snapshot.get("analysis_run", {})
    health = snapshot.get("health", {})
    summary = snapshot.get("summary", {})
    findings = snapshot.get("findings", [])

    lines: list[str] = [
        "CONTROLCHECK AI",
        _ascii(snapshot.get("report_name", "Project Control Report")),
        f"Project: {_ascii(project.get('code'))} - {_ascii(project.get('name'))}",
        f"Period: {_ascii(snapshot.get('period'))}",
        f"Analysis Run: {_ascii(run.get('id'))}",
        f"Generated: {_ascii(snapshot.get('generated_at'))}",
        f"Generated By: {_ascii(snapshot.get('generated_by_name'))}",
        "",
        "EXECUTIVE SUMMARY",
        f"Overall Health: {_ascii(health.get('overall_score'))} ({_ascii(health.get('score_band') or health.get('status_label'))})",
        f"Data Quality: {_ascii(health.get('data_quality_score'))}",
        f"Open Critical: {_ascii(summary.get('open_critical'))}",
        f"Open Warning: {_ascii(summary.get('open_warning'))}",
        f"Resolved Findings: {_ascii(summary.get('resolved'))}",
        f"Total Findings: {_ascii(summary.get('total_findings'))}",
        "",
        "FINDINGS",
    ]

    for idx, finding in enumerate(findings, start=1):
        lines.extend(
            [
                f"{idx}. [{_ascii(finding.get('severity')).upper()}] {_ascii(finding.get('title'))}",
                f"   Status: {_ascii(finding.get('status'))} | Category: {_ascii(finding.get('category'))} | Rule: {_ascii(finding.get('rule_id'))}",
            ]
        )
        for wrapped in _wrap(finding.get("description") or "", 86):
            lines.append(f"   {wrapped}")
        if finding.get("recommendation"):
            for wrapped in _wrap(f"Action: {finding.get('recommendation')}", 86):
                lines.append(f"   {wrapped}")

    lines.extend(["", "EVIDENCE APPENDIX"])
    evidence_index = 0
    for finding in findings:
        evidence = finding.get("evidence", []) or []
        if not evidence:
            continue
        lines.append(f"Finding: {_ascii(finding.get('title'))}")
        for item in evidence:
            evidence_index += 1
            source_rows = ", ".join(str(row) for row in (item.get("source_rows") or [])) or "linked"
            lines.append(f"  E{evidence_index}: {_ascii(item.get('source_sheet'))} | Rows: {_ascii(source_rows)}")
            fields = item.get("fields") or {}
            if fields:
                field_text = "; ".join(f"{k}={v}" for k, v in list(fields.items())[:8])
                for wrapped in _wrap(field_text, 82):
                    lines.append(f"     {wrapped}")

    if evidence_index == 0:
        lines.append("No traceable evidence records were available in this snapshot.")

    # Page layout: 54 lines/page, 10pt Helvetica with 12pt leading.
    pages: list[list[str]] = []
    page: list[str] = []
    for line in lines:
        page.append(line)
        if len(page) >= 54:
            pages.append(page)
            page = []
    if page or not pages:
        pages.append(page)

    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"")  # pages object populated after page objects are known
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    page_object_ids: list[int] = []

    for page_lines in pages:
        commands = ["BT", "/F1 10 Tf", "12 TL", "50 792 Td"]
        first = True
        for line in page_lines:
            if not first:
                commands.append("T*")
            first = False
            commands.append(f"({_pdf_escape(_ascii(line))}) Tj")
        commands.append("ET")
        stream = "\n".join(commands).encode("latin-1", "replace")
        content_obj = f"<< /Length {len(stream)} >>\nstream\n".encode() + stream + b"\nendstream"
        content_id = len(objects) + 1
        objects.append(content_obj)
        page_id = len(objects) + 1
        page_object_ids.append(page_id)
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_id} 0 R >>".encode()
        )

    kids = " ".join(f"{obj_id} 0 R" for obj_id in page_object_ids)
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_object_ids)} >>".encode()

    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for idx, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{idx} 0 obj\n".encode())
        output.extend(obj)
        output.extend(b"\nendobj\n")

    xref_offset = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode())
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode())
    output.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode()
    )
    return bytes(output)
