"""Phase 4A persistence schema.

Revision ID: 20260817_0001
Revises:
"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260817_0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("organizations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("slug", sa.String(100), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("status IN ('active','suspended')", name="ck_organizations_status"))
    op.create_table("projects", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(80), nullable=False), sa.Column("name", sa.String(250), nullable=False), sa.Column("currency", sa.String(3), nullable=False, server_default="IDR"), sa.Column("planned_start", sa.Date), sa.Column("planned_finish", sa.Date), sa.Column("status", sa.String(20), nullable=False, server_default="planning"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("organization_id", "code", name="uq_projects_org_code"), sa.CheckConstraint("status IN ('planning','active','on_hold','completed','closed')", name="ck_projects_status"), sa.CheckConstraint("planned_finish IS NULL OR planned_start IS NULL OR planned_finish >= planned_start", name="ck_projects_dates"))
    op.create_index("ix_projects_organization_id", "projects", ["organization_id"])
    op.create_table("source_files", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("file_name", sa.String(255), nullable=False), sa.Column("storage_key", sa.Text, nullable=False), sa.Column("mime_type", sa.String(100), nullable=False), sa.Column("file_size_bytes", sa.Integer, nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("file_size_bytes >= 0", name="ck_source_files_size"), sa.CheckConstraint("char_length(sha256) = 64", name="ck_source_files_sha256"))
    op.create_table("dataset_snapshots", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("source_file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("source_files.id", ondelete="RESTRICT"), nullable=False), sa.Column("dataset_version", sa.String(20), nullable=False), sa.Column("data_date", sa.Date, nullable=False), sa.Column("source_project_id", sa.String(100), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="validated"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("status IN ('validated','failed')", name="ck_dataset_snapshots_status"))
    op.create_table("rule_catalogue_versions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("version", sa.String(20), nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("definition", postgresql.JSONB, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("version", "sha256", name="uq_catalogue_version_hash"), sa.CheckConstraint("char_length(sha256) = 64", name="ck_catalogue_sha256"))
    op.create_table("analysis_runs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("dataset_snapshot_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dataset_snapshots.id", ondelete="RESTRICT"), nullable=False), sa.Column("catalogue_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("rule_catalogue_versions.id", ondelete="RESTRICT"), nullable=False), sa.Column("engine_version", sa.String(20), nullable=False), sa.Column("workbook_sha256", sa.String(64), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="running"), sa.Column("rule_count", sa.Integer, nullable=False, server_default="0"), sa.Column("finding_count", sa.Integer, nullable=False, server_default="0"), sa.Column("duration_ms", sa.Integer), sa.Column("safe_error_code", sa.String(80)), sa.Column("safe_error_message", sa.Text), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('queued','running','succeeded','failed')", name="ck_analysis_runs_status"), sa.CheckConstraint("rule_count >= 0 AND finding_count >= 0", name="ck_analysis_runs_counts"), sa.CheckConstraint("duration_ms IS NULL OR duration_ms >= 0", name="ck_analysis_runs_duration"), sa.CheckConstraint("char_length(workbook_sha256) = 64", name="ck_analysis_runs_sha256"))
    op.create_table("findings", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("analysis_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analysis_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("engine_finding_id", sa.String(64), nullable=False), sa.Column("rule_id", sa.String(40), nullable=False), sa.Column("rule_name", sa.String(200), nullable=False), sa.Column("entity_type", sa.String(40), nullable=False), sa.Column("entity_id", sa.String(300), nullable=False), sa.Column("category", sa.String(40), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="open"), sa.Column("title", sa.String(300), nullable=False), sa.Column("description", sa.Text, nullable=False), sa.Column("metrics", postgresql.JSONB, nullable=False), sa.Column("calculation", postgresql.JSONB, nullable=False), sa.Column("business_impact", sa.Text, nullable=False), sa.Column("recommendation", sa.Text, nullable=False), sa.Column("confidence", sa.Numeric(5, 4), nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("analysis_run_id", "engine_finding_id", name="uq_findings_run_engine_id"), sa.CheckConstraint("severity IN ('critical','warning','observation')", name="ck_findings_severity"), sa.CheckConstraint("status IN ('open','acknowledged','resolved','dismissed')", name="ck_findings_status"), sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_findings_confidence"))
    op.create_table("finding_evidence", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("finding_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("findings.id", ondelete="CASCADE"), nullable=False), sa.Column("evidence_order", sa.Integer, nullable=False), sa.Column("source_sheet", sa.String(100), nullable=False), sa.Column("source_rows", postgresql.JSONB, nullable=False), sa.Column("record_ids", postgresql.JSONB, nullable=False), sa.Column("fields", postgresql.JSONB, nullable=False), sa.Column("aggregation", postgresql.JSONB), sa.UniqueConstraint("finding_id", "evidence_order", name="uq_evidence_order"))
    op.create_table("approved_exceptions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE")), sa.Column("rule_id", sa.String(40), nullable=False), sa.Column("entity_type", sa.String(40)), sa.Column("entity_id", sa.String(300)), sa.Column("rationale", sa.Text, nullable=False), sa.Column("approver_reference", sa.String(200), nullable=False), sa.Column("evidence_reference", sa.Text, nullable=False), sa.Column("effective_from", sa.Date, nullable=False), sa.Column("effective_to", sa.Date), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("status IN ('active','expired','revoked')", name="ck_exceptions_status"), sa.CheckConstraint("effective_to IS NULL OR effective_to >= effective_from", name="ck_exceptions_dates"))
    op.create_table("audit_logs", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(80)), sa.Column("entity_id", sa.String(100)), sa.Column("metadata", postgresql.JSONB), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    for table, columns in {
        "source_files": ("organization_id", "project_id", "sha256"),
        "dataset_snapshots": ("organization_id", "project_id"),
        "analysis_runs": ("organization_id", "project_id", "status"),
        "findings": ("analysis_run_id", "organization_id", "project_id", "rule_id", "entity_id", "category", "severity", "status"),
        "finding_evidence": ("finding_id",),
        "approved_exceptions": ("organization_id", "project_id", "rule_id"),
        "audit_logs": ("organization_id", "project_id"),
    }.items():
        for column in columns:
            op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("audit_logs", "approved_exceptions", "finding_evidence", "findings", "analysis_runs", "rule_catalogue_versions", "dataset_snapshots", "source_files", "projects", "organizations"):
        op.drop_table(table)
